# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 200390cea6818a179fa1fdbe444d6264ca56247cbedf3c0e4855873acdfdff7e65dd8ee1ef607f65d6daa6abf90d4c278dab305aa8ebbf802d19e534a95d6a47

test:
  secret_key_base: fb226cfa28284d5a9628f675340e54e872b595bd65402e8bee470cdda306de0b1fd9be818ba392843474c88cda582dfa28af33aa83ff1e24df5fd6a433786ba5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
